const {
    analyzeDeepAssessment
} = require("./deepAssessmentService");

const {
    getScholarshipRecommendation
} = require("../rag/ragService");


/**
 * Dashboard Service
 *
 * Combines existing AI services into one dashboard response.
 *
 * Flow:
 *
 * answers
 *   |
 *   v
 * Deep Assessment
 *   |
 *   +--> assessment
 *   |
 *   +--> student profile
 *              |
 *              v
 *       Scholarship Recommendation
 *              |
 *              +--> scholarships
 *              +--> roadmap
 *              +--> AI recommendation
 *
 * Dashboard then combines these outputs.
 */

async function generateDashboard(data) {

    const {
        answers,
        uploads = {}
    } = data;


    if (!answers) {

        throw new Error(
            "Assessment answers are required"
        );

    }


    // 1. Analyze Deep Assessment

    const deepAssessment =
        analyzeDeepAssessment(
            answers,
            uploads
        );


    // 2. Get scholarship recommendations
    //    using the profile generated by Deep Assessment

    const scholarshipResult =
        await getScholarshipRecommendation(
            deepAssessment.profile
        );


    // 3. Generate dashboard insights

    const insights =
        generateInsights(
            deepAssessment,
            scholarshipResult
        );


    // 4. Build dashboard response

    return {

        assessment:
            deepAssessment.assessment,


        scholarships: {

            recommended:
                scholarshipResult.recommendedScholarships,

            aiRecommendation:
                scholarshipResult.aiRecommendation

        },


        roadmap:
            scholarshipResult.roadmap,


        insights

    };

}


/**
 * Generate simple dashboard-level insights.
 *
 * This intentionally remains deterministic for the MVP.
 * We can later replace/enhance this with a dedicated
 * AI insight generator without changing the dashboard API.
 */

function generateInsights(
    deepAssessment,
    scholarshipResult
) {

    const score =
        deepAssessment
            .assessment
            .revised_percentage;


    const readinessLevel =
        getReadinessLevel(score);


    const recommendations =
        scholarshipResult
            .recommendedScholarships || [];


    const insights = {

        readiness_level:
            readinessLevel,


        scholarship_count:
            recommendations.length,


        top_scholarship:
            recommendations.length > 0
                ? recommendations[0].metadata?.name || null
                : null,


        next_step:
            deepAssessment
                .assessment
                .suggestion

    };


    return insights;

}


/**
 * Convert readiness percentage
 * into a dashboard-friendly level.
 */

function getReadinessLevel(score) {

    if (score >= 85) {

        return "Highly Competitive";

    }


    if (score >= 70) {

        return "Competitive";

    }


    if (score >= 50) {

        return "Developing";

    }


    return "Early Preparation";

}


module.exports = {

    generateDashboard

};